"""Shared fixtures. Workstreams: do NOT edit this file — put extra fixtures in your own test
module or in tests/helpers/<area>.py."""

import os

# Settings must be in place before any app module caches them.
os.environ.setdefault("DATABASE_URL", "sqlite+aiosqlite:///:memory:")
os.environ.setdefault("REDIS_URL", "redis://unused:6379/0")
os.environ.setdefault("JWT_SECRET", "test-jwt-secret-test-jwt-secret-0123456789")
os.environ.setdefault("TOKEN_ENCRYPTION_KEY", "ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg=")
os.environ.setdefault("AUTH_BRIDGE_SECRET", "test-bridge-secret")
os.environ.setdefault("TRUSTED_PROXIES", "172.16.0.0/12,127.0.0.1/32")
os.environ.setdefault("GITHUB_ADMIN_IDS", "500")
os.environ.setdefault("GITHUB_REVIEWER_ORGS", "acme")
os.environ.setdefault("GITHUB_VIEWER_ORGS", "acme-readers")
os.environ.setdefault("ANTHROPIC_API_KEY", "")
os.environ.setdefault("LANGFUSE_PUBLIC_KEY", "")
os.environ.setdefault("LANGFUSE_SECRET_KEY", "")


def pytest_addoption(parser):
    parser.addoption("--run-live", action="store_true", default=False, help="run tests marked live")


def pytest_collection_modifyitems(config, items):
    if config.getoption("--run-live"):
        return
    import pytest

    skip = pytest.mark.skip(reason="live test: pass --run-live (needs network + API keys)")
    for item in items:
        if "live" in item.keywords:
            item.add_marker(skip)


import fakeredis  # noqa: E402
import httpx  # noqa: E402
import pytest  # noqa: E402
import pytest_asyncio  # noqa: E402
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine  # noqa: E402
from sqlalchemy.pool import StaticPool  # noqa: E402

from app import db as app_db  # noqa: E402
from app.db import Base, get_session  # noqa: E402
from app.models import Role, User  # noqa: E402
from app.redis_client import get_redis  # noqa: E402
from app.security import mint_jwt  # noqa: E402


@pytest_asyncio.fixture
async def engine():
    eng = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    async with eng.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    yield eng
    await eng.dispose()


@pytest_asyncio.fixture
async def sessionmaker(engine):
    maker = async_sessionmaker(engine, expire_on_commit=False)
    app_db.set_sessionmaker(maker)  # background tasks open sessions through app.db
    return maker


@pytest_asyncio.fixture
async def session(sessionmaker):
    async with sessionmaker() as s:
        yield s


@pytest_asyncio.fixture
async def redis():
    r = fakeredis.FakeAsyncRedis(decode_responses=True)
    yield r
    await r.flushall()
    await r.aclose()


@pytest_asyncio.fixture
async def app(sessionmaker, redis):
    from app.main import create_app

    application = create_app()

    async def _session():
        async with sessionmaker() as s:
            yield s

    application.dependency_overrides[get_session] = _session
    application.dependency_overrides[get_redis] = lambda: redis
    return application


@pytest_asyncio.fixture
async def client(app):
    transport = httpx.ASGITransport(app=app, client=("203.0.113.7", 50000))
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as c:
        yield c


_next_github_id = [1000]


@pytest.fixture
def make_user(session):
    async def _make(role: Role = Role.reviewer, login: str | None = None, **kw) -> User:
        _next_github_id[0] += 1
        gid = _next_github_id[0]
        user = User(
            github_id=kw.pop("github_id", gid),
            github_login=login or f"user{gid}",
            email=kw.pop("email", f"user{gid}@example.com"),
            role=role,
            is_active=kw.pop("is_active", True),
            **kw,
        )
        session.add(user)
        await session.commit()
        await session.refresh(user)
        return user

    return _make


@pytest.fixture
def auth_headers():
    def _headers(user: User) -> dict[str, str]:
        token, _ = mint_jwt(user.id)
        return {"Authorization": f"Bearer {token}"}

    return _headers
